- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "/home/{{ username }}/yay"
    update: true

- name: Build and install yay
  command:
    chdir: "/home/{{ username }}/yay"
    cmd: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay