- name: install basic stuff
  community.general.pacman:
   name:
   # Terminal
    - kitty
    - tmux


    #DownloadUtil
    - git
    - wget
    - curl
    # CLI and vim
    - thefuck
    - lsd
    - vim
    - source-highlight
    - tree
    - base-devel
    #Firewall
    - ufw
    #Screenshot, background and grafic
    - flameshot
    - gimp
    - variety
    - feh
    # bluetooth and audio
    - bluez
    - bluez-utils
    - blueman
    - pipewire
    - pipewire-pulse
    # ziptools
    - atool
    - p7zip
    - unrar
    - unzip
    - xz
    - tar
    - gzip
    - bzip2
    - zip
    #
   state: present


