- name: check updates
  pacman: 
   update_cache: yes
   upgrade: yes


# Configure pacman (colorize and repos)
- include_tasks: pacman.yml

# Basic apps (vlc, kitty, etc.)
- include_tasks: core-apps.yml

# Install and configure zsh
- include_tasks: zsh.yml
  when: setup_zsh == True

# Install and configure neovim
- include_tasks: neovim.yml
  when: install_neovim == True


# Web Browser
- include_tasks: "firefox.yml"

# Office
- include_tasks: office.yml
  when: install_office == True

# obsidian
- include_tasks: obsidian.yml
  when: install_obsidian == True
  
# AUR apps
- include_tasks: aur.yml
  when: use_aur == True

# Dotfiles
- include_tasks: dotfiles.yml
  when: pull_dotfiles == True


# Thundar
- include_tasks: thunar.yml
  when: install_thunar == True


# yay apps
- include_tasks: yay.yml
  when: install_yay_apps == True
